//! Purpose:
//! Dispatches one bounded generated group of typed builtin runtime targets.
//! This file is generated by `scripts/migrate_builtin_backend_targets.py`.
//!
//! Called from:
//! - `super::lower()` while lowering typed EIR runtime calls.
//!
//! Key details:
//! - Dispatch is by enum identity, never by PHP function-name strings.
//! - Extracted bodies remain thin calls into target-aware backend emitters.

use crate::codegen::context::FunctionContext;
use crate::codegen::Result;
use crate::ir::{BuiltinRuntimeTarget, Instruction};

/// Lowers a target owned by generated dispatch group 11, or returns `None`.
pub(super) fn lower(
    ctx: &mut FunctionContext<'_>,
    inst: &Instruction,
    target: BuiltinRuntimeTarget,
) -> Option<Result<()>> {
    match target {
        BuiltinRuntimeTarget::ClassAttributeNames => Some({
            crate::codegen::lower_inst::builtins::attributes::lower_class_attribute_names(ctx, inst)
        }),
        BuiltinRuntimeTarget::ClassGetAttributes => Some({
            crate::codegen::lower_inst::builtins::attributes::lower_class_get_attributes(ctx, inst)
        }),
        BuiltinRuntimeTarget::Date => Some({
            crate::codegen::lower_inst::builtins::system::lower_date(ctx, inst)
        }),
        BuiltinRuntimeTarget::DateDefaultTimezoneGet => Some({
            crate::codegen::lower_inst::builtins::system::lower_date_default_timezone_get(ctx, inst)
        }),
        BuiltinRuntimeTarget::DateDefaultTimezoneSet => Some({
            crate::codegen::lower_inst::builtins::system::lower_date_default_timezone_set(ctx, inst)
        }),
        BuiltinRuntimeTarget::Define => Some({
            crate::codegen::lower_inst::builtins::lower_define(ctx, inst)
        }),
        BuiltinRuntimeTarget::Defined => Some({
            crate::codegen::lower_inst::builtins::lower_defined(ctx, inst)
        }),
        BuiltinRuntimeTarget::Exec => Some({
            crate::codegen::lower_inst::builtins::system::lower_exec(ctx, inst)
        }),
        BuiltinRuntimeTarget::Getdate => Some({
            crate::codegen::lower_inst::builtins::system::lower_getdate(ctx, inst)
        }),
        BuiltinRuntimeTarget::Getenv => Some({
            crate::codegen::lower_inst::builtins::system::lower_getenv(ctx, inst)
        }),
        BuiltinRuntimeTarget::Gmdate => Some({
            crate::codegen::lower_inst::builtins::system::lower_gmdate(ctx, inst)
        }),
        BuiltinRuntimeTarget::Gmmktime => Some({
            crate::codegen::lower_inst::builtins::system::lower_gmmktime(ctx, inst)
        }),
        BuiltinRuntimeTarget::Header => Some({
            crate::codegen::lower_inst::builtins::system::lower_header(ctx, inst)
        }),
        BuiltinRuntimeTarget::Hrtime => Some({
            crate::codegen::lower_inst::builtins::system::lower_hrtime(ctx, inst)
        }),
        BuiltinRuntimeTarget::HttpResponseCode => Some({
            crate::codegen::lower_inst::builtins::system::lower_http_response_code(ctx, inst)
        }),
        BuiltinRuntimeTarget::JsonDecode => Some({
            crate::codegen::lower_inst::builtins::json::lower_json_decode(ctx, inst)
        }),
        BuiltinRuntimeTarget::JsonEncode => Some({
            crate::codegen::lower_inst::builtins::json::lower_json_encode(ctx, inst)
        }),
        BuiltinRuntimeTarget::JsonLastError => Some({
            crate::codegen::lower_inst::builtins::json::lower_json_last_error(ctx, inst)
        }),
        BuiltinRuntimeTarget::JsonLastErrorMsg => Some({
            crate::codegen::lower_inst::builtins::json::lower_json_last_error_msg(ctx, inst)
        }),
        BuiltinRuntimeTarget::JsonValidate => Some({
            crate::codegen::lower_inst::builtins::json::lower_json_validate(ctx, inst)
        }),
        BuiltinRuntimeTarget::Localtime => Some({
            crate::codegen::lower_inst::builtins::system::lower_localtime(ctx, inst)
        }),
        BuiltinRuntimeTarget::Microtime => Some({
            crate::codegen::lower_inst::builtins::system::lower_microtime(ctx, inst)
        }),
        BuiltinRuntimeTarget::Mktime => Some({
            crate::codegen::lower_inst::builtins::system::lower_mktime(ctx, inst)
        }),
        BuiltinRuntimeTarget::Passthru => Some({
            crate::codegen::lower_inst::builtins::system::lower_passthru(ctx, inst)
        }),
        BuiltinRuntimeTarget::PhpUname => Some({
            crate::codegen::lower_inst::builtins::system::lower_php_uname(ctx, inst)
        }),
        BuiltinRuntimeTarget::Phpversion => Some({
            crate::codegen::lower_inst::builtins::lower_phpversion(ctx, inst)
        }),
        BuiltinRuntimeTarget::PregMatch => Some({
            crate::codegen::lower_inst::builtins::regex::lower_preg_match(ctx, inst)
        }),
        BuiltinRuntimeTarget::PregMatchAll => Some({
            crate::codegen::lower_inst::builtins::regex::lower_preg_match_all(ctx, inst)
        }),
        BuiltinRuntimeTarget::PregReplace => Some({
            crate::codegen::lower_inst::builtins::regex::lower_preg_replace(ctx, inst)
        }),
        BuiltinRuntimeTarget::PregSplit => Some({
            crate::codegen::lower_inst::builtins::regex::lower_preg_split(ctx, inst)
        }),
        BuiltinRuntimeTarget::Putenv => Some({
            crate::codegen::lower_inst::builtins::system::lower_putenv(ctx, inst)
        }),
        BuiltinRuntimeTarget::Serialize => Some({
            crate::codegen::lower_inst::builtins::serialize::lower_serialize(ctx, inst)
        }),
        BuiltinRuntimeTarget::ShellExec => Some({
            crate::codegen::lower_inst::builtins::system::lower_shell_exec(ctx, inst)
        }),
        BuiltinRuntimeTarget::Sleep => Some({
            crate::codegen::lower_inst::builtins::system::lower_sleep(ctx, inst)
        }),
        BuiltinRuntimeTarget::Strtotime => Some({
            crate::codegen::lower_inst::builtins::system::lower_strtotime(ctx, inst)
        }),
        _ => None,
    }
}
