//! Purpose:
//! Dispatches one bounded generated group of typed builtin runtime targets.
//! This file is generated by `scripts/migrate_builtin_backend_targets.py`.
//!
//! Called from:
//! - `super::lower()` while lowering typed EIR runtime calls.
//!
//! Key details:
//! - Dispatch is by enum identity, never by PHP function-name strings.
//! - Extracted bodies remain thin calls into target-aware backend emitters.

use crate::codegen::context::FunctionContext;
use crate::codegen::Result;
use crate::ir::{BuiltinRuntimeTarget, Instruction};

/// Lowers a target owned by generated dispatch group 10, or returns `None`.
pub(super) fn lower(
    ctx: &mut FunctionContext<'_>,
    inst: &Instruction,
    target: BuiltinRuntimeTarget,
) -> Option<Result<()>> {
    match target {
        BuiltinRuntimeTarget::MbStrlen => Some({
            crate::codegen::lower_inst::builtins::strings::lower_mb_strlen(ctx, inst)
        }),
        BuiltinRuntimeTarget::Md5 => Some({
            crate::codegen::lower_inst::builtins::strings::lower_md5(ctx, inst)
        }),
        BuiltinRuntimeTarget::NumberFormat => Some({
            crate::codegen::lower_inst::builtins::strings::lower_number_format(ctx, inst)
        }),
        BuiltinRuntimeTarget::Ord => Some({
            crate::codegen::lower_inst::builtins::strings::lower_ord(ctx, inst)
        }),
        BuiltinRuntimeTarget::Printf => Some({
            crate::codegen::lower_inst::builtins::strings::lower_printf(ctx, inst)
        }),
        BuiltinRuntimeTarget::Rtrim => Some({
            crate::codegen::lower_inst::builtins::strings::lower_trim_like(
                    ctx,
                    inst,
                    "rtrim",
                    "__rt_rtrim",
                    "__rt_rtrim_mask",
                )
        }),
        BuiltinRuntimeTarget::Sha1 => Some({
            crate::codegen::lower_inst::builtins::strings::lower_sha1(ctx, inst)
        }),
        BuiltinRuntimeTarget::Sprintf => Some({
            crate::codegen::lower_inst::builtins::strings::lower_sprintf(ctx, inst)
        }),
        BuiltinRuntimeTarget::Sscanf => Some({
            crate::codegen::lower_inst::builtins::strings::lower_sscanf(ctx, inst)
        }),
        BuiltinRuntimeTarget::StrContains => Some({
            crate::codegen::lower_inst::builtins::strings::lower_str_contains(ctx, inst)
        }),
        BuiltinRuntimeTarget::StrEndsWith => Some({
            crate::codegen::lower_inst::builtins::strings::lower_binary_string_runtime(
                    ctx,
                    inst,
                    "str_ends_with",
                    "__rt_str_ends_with",
                )
        }),
        BuiltinRuntimeTarget::StrIreplace => Some({
            crate::codegen::lower_inst::builtins::strings::lower_string_replace(
                    ctx,
                    inst,
                    "str_ireplace",
                    "__rt_str_ireplace",
                )
        }),
        BuiltinRuntimeTarget::StrPad => Some({
            crate::codegen::lower_inst::builtins::strings::lower_str_pad(ctx, inst)
        }),
        BuiltinRuntimeTarget::StrRepeat => Some({
            crate::codegen::lower_inst::builtins::strings::lower_str_repeat(ctx, inst)
        }),
        BuiltinRuntimeTarget::StrReplace => Some({
            crate::codegen::lower_inst::builtins::strings::lower_string_replace(
                    ctx,
                    inst,
                    "str_replace",
                    "__rt_str_replace",
                )
        }),
        BuiltinRuntimeTarget::StrSplit => Some({
            crate::codegen::lower_inst::builtins::strings::lower_str_split(ctx, inst)
        }),
        BuiltinRuntimeTarget::StrStartsWith => Some({
            crate::codegen::lower_inst::builtins::strings::lower_binary_string_runtime(
                    ctx,
                    inst,
                    "str_starts_with",
                    "__rt_str_starts_with",
                )
        }),
        BuiltinRuntimeTarget::Strcasecmp => Some({
            crate::codegen::lower_inst::builtins::strings::lower_binary_string_runtime(
                    ctx,
                    inst,
                    "strcasecmp",
                    "__rt_strcasecmp",
                )
        }),
        BuiltinRuntimeTarget::Strcmp => Some({
            crate::codegen::lower_inst::builtins::strings::lower_binary_string_runtime(
                    ctx,
                    inst,
                    "strcmp",
                    "__rt_strcmp",
                )
        }),
        BuiltinRuntimeTarget::Strpos => Some({
            crate::codegen::lower_inst::builtins::strings::lower_string_position(
                    ctx,
                    inst,
                    "strpos",
                    "__rt_strpos",
                )
        }),
        BuiltinRuntimeTarget::Strrpos => Some({
            crate::codegen::lower_inst::builtins::strings::lower_string_position(
                    ctx,
                    inst,
                    "strrpos",
                    "__rt_strrpos",
                )
        }),
        BuiltinRuntimeTarget::Strstr => Some({
            crate::codegen::lower_inst::builtins::strings::lower_strstr(ctx, inst)
        }),
        BuiltinRuntimeTarget::Substr => Some({
            crate::codegen::lower_inst::builtins::strings::lower_substr(ctx, inst)
        }),
        BuiltinRuntimeTarget::SubstrReplace => Some({
            crate::codegen::lower_inst::builtins::strings::lower_substr_replace(ctx, inst)
        }),
        BuiltinRuntimeTarget::Trim => Some({
            crate::codegen::lower_inst::builtins::strings::lower_trim_like(
                    ctx,
                    inst,
                    "trim",
                    "__rt_trim",
                    "__rt_trim_mask",
                )
        }),
        BuiltinRuntimeTarget::Ucfirst => Some({
            crate::codegen::lower_inst::builtins::strings::lower_ucfirst(ctx, inst)
        }),
        BuiltinRuntimeTarget::Ucwords => Some({
            crate::codegen::lower_inst::builtins::strings::lower_unary_string_runtime(
                    ctx,
                    inst,
                    "ucwords",
                    "__rt_ucwords",
                )
        }),
        BuiltinRuntimeTarget::Vprintf => Some({
            crate::codegen::lower_inst::builtins::strings::lower_vprintf(ctx, inst)
        }),
        BuiltinRuntimeTarget::Vsprintf => Some({
            crate::codegen::lower_inst::builtins::strings::lower_vsprintf(ctx, inst)
        }),
        BuiltinRuntimeTarget::Wordwrap => Some({
            crate::codegen::lower_inst::builtins::strings::lower_wordwrap(ctx, inst)
        }),
        BuiltinRuntimeTarget::ElephcGmmktimeRaw => Some({
            crate::codegen::lower_inst::builtins::system::lower_gmmktime(ctx, inst)
        }),
        BuiltinRuntimeTarget::ElephcMktimeRaw => Some({
            crate::codegen::lower_inst::builtins::system::lower_mktime(ctx, inst)
        }),
        BuiltinRuntimeTarget::ElephcStrtotimeRaw => Some({
            crate::codegen::lower_inst::builtins::system::lower_elephc_strtotime_raw(ctx, inst)
        }),
        BuiltinRuntimeTarget::Checkdate => Some({
            crate::codegen::lower_inst::builtins::system::lower_checkdate(ctx, inst)
        }),
        BuiltinRuntimeTarget::ClassAttributeArgs => Some({
            crate::codegen::lower_inst::builtins::attributes::lower_class_attribute_args(ctx, inst)
        }),
        _ => None,
    }
}
