//! Purpose:
//! Dispatches one bounded generated group of typed builtin runtime targets.
//! This file is generated by `scripts/migrate_builtin_backend_targets.py`.
//!
//! Called from:
//! - `super::lower()` while lowering typed EIR runtime calls.
//!
//! Key details:
//! - Dispatch is by enum identity, never by PHP function-name strings.
//! - Extracted bodies remain thin calls into target-aware backend emitters.

use crate::codegen::context::FunctionContext;
use crate::codegen::Result;
use crate::ir::{BuiltinRuntimeTarget, Instruction};

/// Lowers a target owned by generated dispatch group 00, or returns `None`.
pub(super) fn lower(
    ctx: &mut FunctionContext<'_>,
    inst: &Instruction,
    target: BuiltinRuntimeTarget,
) -> Option<Result<()>> {
    match target {
        BuiltinRuntimeTarget::ArrayAll => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_all(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayAny => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_any(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayChunk => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_chunk(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayColumn => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_column(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayCombine => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_combine(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayDiff => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_diff(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayDiffAssoc => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_diff_assoc(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayDiffKey => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_diff_key(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayFill => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_fill(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayFillKeys => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_fill_keys(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayFilter => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_filter(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayFind => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_find(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayFlip => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_flip(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayIntersect => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_intersect(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayIntersectAssoc => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_intersect_assoc(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayIntersectKey => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_intersect_key(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayIsList => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_is_list(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayKeyExists => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_key_exists(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayKeyFirst => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_key_first(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayKeyLast => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_key_last(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayKeys => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_keys(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayMap => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_map(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayMerge => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_merge(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayMergeRecursive => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_merge_recursive(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayMultisort => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_multisort(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayPad => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_pad(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayPop => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_pop(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayProduct => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_product(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayPush => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_push(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayRand => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_rand(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayReduce => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_reduce(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayReplace => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_replace(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayReplaceRecursive => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_replace_recursive(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArrayReverse => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_reverse(ctx, inst)
        }),
        BuiltinRuntimeTarget::ArraySearch => Some({
            crate::codegen::lower_inst::builtins::arrays::lower_array_search(ctx, inst)
        }),
        _ => None,
    }
}
