//! Purpose:
//! Dispatches one bounded generated group of typed builtin runtime targets.
//! This file is generated by `scripts/migrate_builtin_backend_targets.py`.
//!
//! Called from:
//! - `super::lower()` while lowering typed EIR runtime calls.
//!
//! Key details:
//! - Dispatch is by enum identity, never by PHP function-name strings.
//! - Extracted bodies remain thin calls into target-aware backend emitters.

use crate::codegen::context::FunctionContext;
use crate::codegen::Result;
use crate::ir::{BuiltinRuntimeTarget, Instruction};

/// Lowers a target owned by generated dispatch group 06, or returns `None`.
pub(super) fn lower(
    ctx: &mut FunctionContext<'_>,
    inst: &Instruction,
    target: BuiltinRuntimeTarget,
) -> Option<Result<()>> {
    match target {
        BuiltinRuntimeTarget::StreamFilterPrepend => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_filter_attach(ctx, inst, "stream_filter_prepend")
        }),
        BuiltinRuntimeTarget::StreamFilterRegister => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_filter_register(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamFilterRemove => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_filter_remove(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamGetContents => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_get_contents(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamGetFilters => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_get_filters(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamGetLine => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_get_line(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamGetMetaData => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_get_meta_data(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamGetTransports => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_get_transports(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamGetWrappers => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_get_wrappers(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamIsLocal => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_is_local(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamIsatty => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_isatty(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamResolveIncludePath => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_resolve_include_path(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSelect => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_select(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSetBlocking => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_set_blocking(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSetChunkSize => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_set_chunk_size(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSetReadBuffer => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_set_buffer(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSetTimeout => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_set_timeout(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSetWriteBuffer => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_set_buffer(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSocketAccept => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_socket_accept(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSocketClient => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_socket_client(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSocketEnableCrypto => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_socket_enable_crypto(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSocketGetName => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_socket_get_name(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSocketPair => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_socket_pair(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSocketRecvfrom => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_socket_recvfrom(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSocketSendto => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_socket_sendto(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSocketServer => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_socket_server(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSocketShutdown => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_socket_shutdown(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamSupportsLock => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_supports_lock(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamWrapperRegister => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_wrapper_register(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamWrapperRestore => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_wrapper_restore(ctx, inst)
        }),
        BuiltinRuntimeTarget::StreamWrapperUnregister => Some({
            crate::codegen::lower_inst::builtins::io::lower_stream_wrapper_unregister(ctx, inst)
        }),
        BuiltinRuntimeTarget::Symlink => Some({
            crate::codegen::lower_inst::builtins::io::lower_symlink(ctx, inst)
        }),
        BuiltinRuntimeTarget::SysGetTempDir => Some({
            crate::codegen::lower_inst::builtins::io::lower_sys_get_temp_dir(ctx, inst)
        }),
        BuiltinRuntimeTarget::Tempnam => Some({
            crate::codegen::lower_inst::builtins::io::lower_tempnam(ctx, inst)
        }),
        BuiltinRuntimeTarget::Tmpfile => Some({
            crate::codegen::lower_inst::builtins::io::lower_tmpfile(ctx, inst)
        }),
        _ => None,
    }
}
