//! Purpose:
//! Dispatches one bounded generated group of typed builtin runtime targets.
//! This file is generated by `scripts/migrate_builtin_backend_targets.py`.
//!
//! Called from:
//! - `super::lower()` while lowering typed EIR runtime calls.
//!
//! Key details:
//! - Dispatch is by enum identity, never by PHP function-name strings.
//! - Extracted bodies remain thin calls into target-aware backend emitters.

use crate::codegen::context::FunctionContext;
use crate::codegen::Result;
use crate::ir::{BuiltinRuntimeTarget, Instruction};

/// Lowers a target owned by generated dispatch group 08, or returns `None`.
pub(super) fn lower(
    ctx: &mut FunctionContext<'_>,
    inst: &Instruction,
    target: BuiltinRuntimeTarget,
) -> Option<Result<()>> {
    match target {
        BuiltinRuntimeTarget::Sqrt => Some({
            crate::codegen::lower_inst::builtins::math::lower_sqrt(ctx, inst)
        }),
        BuiltinRuntimeTarget::Tan => Some({
            crate::codegen::lower_inst::builtins::math::lower_unary_libm(ctx, inst, "tan")
        }),
        BuiltinRuntimeTarget::Tanh => Some({
            crate::codegen::lower_inst::builtins::math::lower_unary_libm(ctx, inst, "tanh")
        }),
        BuiltinRuntimeTarget::ElephcPtrIsNull => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_is_null(ctx, inst)
        }),
        BuiltinRuntimeTarget::ElephcPtrReadString => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_read_string(ctx, inst)
        }),
        BuiltinRuntimeTarget::ElephcPtrWriteString => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_write_string(ctx, inst)
        }),
        BuiltinRuntimeTarget::BufferFree => Some({
            crate::codegen::lower_inst::builtins::buffers::lower_buffer_free(ctx, inst)
        }),
        BuiltinRuntimeTarget::BufferLen => Some({
            crate::codegen::lower_inst::builtins::buffers::lower_buffer_len(ctx, inst)
        }),
        BuiltinRuntimeTarget::Ptr => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrGet => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_get(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrIsNull => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_is_null(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrNull => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_null(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrOffset => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_offset(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrRead16 => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_read16(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrRead32 => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_read32(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrRead8 => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_read8(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrReadString => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_read_string(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrSet => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_set(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrSizeof => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_sizeof(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrWrite16 => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_write16(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrWrite32 => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_write32(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrWrite8 => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_write8(ctx, inst)
        }),
        BuiltinRuntimeTarget::PtrWriteString => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_ptr_write_string(ctx, inst)
        }),
        BuiltinRuntimeTarget::ZvalFree => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_zval_free(ctx, inst)
        }),
        BuiltinRuntimeTarget::ZvalPack => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_zval_pack(ctx, inst)
        }),
        BuiltinRuntimeTarget::ZvalType => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_zval_type(ctx, inst)
        }),
        BuiltinRuntimeTarget::ZvalUnpack => Some({
            crate::codegen::lower_inst::builtins::pointers::lower_zval_unpack(ctx, inst)
        }),
        BuiltinRuntimeTarget::IteratorApply => Some({
            crate::codegen::lower_inst::builtins::spl::lower_iterator_apply(ctx, inst)
        }),
        BuiltinRuntimeTarget::IteratorCount => Some({
            crate::codegen::lower_inst::builtins::spl::lower_iterator_count(ctx, inst)
        }),
        BuiltinRuntimeTarget::IteratorToArray => Some({
            crate::codegen::lower_inst::builtins::spl::lower_iterator_to_array(ctx, inst)
        }),
        BuiltinRuntimeTarget::SplAutoload => Some({
            crate::codegen::lower_inst::builtins::spl::lower_spl_autoload_void(
                    ctx,
                    inst,
                    "spl_autoload",
                )
        }),
        BuiltinRuntimeTarget::SplAutoloadCall => Some({
            crate::codegen::lower_inst::builtins::spl::lower_spl_autoload_void(
                    ctx,
                    inst,
                    "spl_autoload_call",
                )
        }),
        BuiltinRuntimeTarget::SplAutoloadExtensions => Some({
            crate::codegen::lower_inst::builtins::spl::lower_spl_autoload_extensions(ctx, inst)
        }),
        BuiltinRuntimeTarget::SplAutoloadFunctions => Some({
            crate::codegen::lower_inst::builtins::spl::lower_spl_autoload_functions(ctx, inst)
        }),
        BuiltinRuntimeTarget::SplAutoloadRegister => Some({
            crate::codegen::lower_inst::builtins::spl::lower_spl_autoload_bool(
                    ctx,
                    inst,
                    "spl_autoload_register",
                )
        }),
        _ => None,
    }
}
