//! Purpose:
//! Defines stable typed identities for registry builtin backend operations.
//! This file is generated by `scripts/migrate_builtin_backend_targets.py`.
//!
//! Called from:
//! - Registry semantic descriptors and typed EIR `RuntimeCall` instructions.
//! - Target backend dispatch groups under `codegen/lower_inst/builtin_runtime_targets/`.
//!
//! Key details:
//! - Variants are semantic identities; backend dispatch never infers behavior from PHP names.
//! - Physical registers, helper symbols, and platform branches remain downstream in codegen.

/// Stable semantic identity for one registry builtin backend operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BuiltinRuntimeTarget {
    ArrayAll,
    ArrayAny,
    ArrayChunk,
    ArrayColumn,
    ArrayCombine,
    ArrayDiff,
    ArrayDiffAssoc,
    ArrayDiffKey,
    ArrayFill,
    ArrayFillKeys,
    ArrayFilter,
    ArrayFind,
    ArrayFlip,
    ArrayIntersect,
    ArrayIntersectAssoc,
    ArrayIntersectKey,
    ArrayIsList,
    ArrayKeyExists,
    ArrayKeyFirst,
    ArrayKeyLast,
    ArrayKeys,
    ArrayMap,
    ArrayMerge,
    ArrayMergeRecursive,
    ArrayMultisort,
    ArrayPad,
    ArrayPop,
    ArrayProduct,
    ArrayPush,
    ArrayRand,
    ArrayReduce,
    ArrayReplace,
    ArrayReplaceRecursive,
    ArrayReverse,
    ArraySearch,
    ArrayShift,
    ArraySlice,
    ArraySplice,
    ArraySum,
    ArrayUdiff,
    ArrayUintersect,
    ArrayUnique,
    ArrayUnshift,
    ArrayValues,
    ArrayWalk,
    ArrayWalkRecursive,
    Arsort,
    Asort,
    Count,
    InArray,
    Krsort,
    Ksort,
    Natcasesort,
    Natsort,
    Range,
    Rsort,
    Shuffle,
    Sort,
    Uasort,
    Uksort,
    Usort,
    CallUserFunc,
    CallUserFuncArray,
    ClassAlias,
    ClassExists,
    ClassImplements,
    ClassParents,
    ClassUses,
    EnumExists,
    FunctionExists,
    GetClass,
    GetDeclaredClasses,
    GetDeclaredInterfaces,
    GetDeclaredTraits,
    GetParentClass,
    InterfaceExists,
    IsA,
    IsSubclassOf,
    MethodExists,
    PregReplaceCallback,
    PropertyExists,
    TraitExists,
    ElephcPharBzip2Archive,
    ElephcPharDecompressArchive,
    ElephcPharGetFileMetadata,
    ElephcPharGetMetadata,
    ElephcPharGetSignatureHash,
    ElephcPharGetSignatureType,
    ElephcPharGetStub,
    ElephcPharGzipArchive,
    ElephcPharListEntries,
    ElephcPharSetCompression,
    ElephcPharSetFileMetadata,
    ElephcPharSetMetadata,
    ElephcPharSetStub,
    ElephcPharSetZipPassword,
    ElephcPharSignHash,
    ElephcPharSignOpenssl,
    Basename,
    Chdir,
    Chgrp,
    Chmod,
    Chown,
    Clearstatcache,
    Closedir,
    Copy,
    Dirname,
    DiskFreeSpace,
    DiskTotalSpace,
    Fclose,
    Fdatasync,
    Feof,
    Fflush,
    Fgetc,
    Fgetcsv,
    Fgets,
    File,
    FileExists,
    FileGetContents,
    FilePutContents,
    Fileatime,
    Filectime,
    Filegroup,
    Fileinode,
    Filemtime,
    Fileowner,
    Fileperms,
    Filesize,
    Filetype,
    Flock,
    Fnmatch,
    Fopen,
    Fpassthru,
    Fprintf,
    Fputcsv,
    Fread,
    Fscanf,
    Fseek,
    Fsockopen,
    Fstat,
    Fsync,
    Ftell,
    Ftruncate,
    Fwrite,
    Getcwd,
    Gethostbyaddr,
    Gethostbyname,
    Gethostname,
    Getprotobyname,
    Getprotobynumber,
    Getservbyname,
    Getservbyport,
    Glob,
    HashFile,
    IsDir,
    IsExecutable,
    IsFile,
    IsLink,
    IsReadable,
    IsWritable,
    IsWriteable,
    Lchgrp,
    Lchown,
    Link,
    Linkinfo,
    Lstat,
    Mkdir,
    ObClean,
    ObEndClean,
    ObEndFlush,
    ObFlush,
    ObGetClean,
    ObGetContents,
    ObGetFlush,
    ObGetLength,
    ObGetLevel,
    ObGetStatus,
    ObImplicitFlush,
    ObListHandlers,
    ObStart,
    Opendir,
    Pathinfo,
    Pclose,
    Pfsockopen,
    Popen,
    PrintR,
    Readdir,
    Readfile,
    Readline,
    Readlink,
    Realpath,
    RealpathCacheGet,
    RealpathCacheSize,
    Rename,
    Rewind,
    Rewinddir,
    Rmdir,
    Scandir,
    Stat,
    StreamBucketAppend,
    StreamBucketMakeWriteable,
    StreamBucketNew,
    StreamBucketPrepend,
    StreamContextCreate,
    StreamContextGetDefault,
    StreamContextGetOptions,
    StreamContextGetParams,
    StreamContextSetDefault,
    StreamContextSetOption,
    StreamContextSetParams,
    StreamCopyToStream,
    StreamFilterAppend,
    StreamFilterPrepend,
    StreamFilterRegister,
    StreamFilterRemove,
    StreamGetContents,
    StreamGetFilters,
    StreamGetLine,
    StreamGetMetaData,
    StreamGetTransports,
    StreamGetWrappers,
    StreamIsLocal,
    StreamIsatty,
    StreamResolveIncludePath,
    StreamSelect,
    StreamSetBlocking,
    StreamSetChunkSize,
    StreamSetReadBuffer,
    StreamSetTimeout,
    StreamSetWriteBuffer,
    StreamSocketAccept,
    StreamSocketClient,
    StreamSocketEnableCrypto,
    StreamSocketGetName,
    StreamSocketPair,
    StreamSocketRecvfrom,
    StreamSocketSendto,
    StreamSocketServer,
    StreamSocketShutdown,
    StreamSupportsLock,
    StreamWrapperRegister,
    StreamWrapperRestore,
    StreamWrapperUnregister,
    Symlink,
    SysGetTempDir,
    Tempnam,
    Tmpfile,
    Touch,
    Umask,
    Unlink,
    VarDump,
    Vfprintf,
    Abs,
    Acos,
    Asin,
    Atan,
    Atan2,
    Ceil,
    Clamp,
    Cos,
    Cosh,
    Deg2rad,
    Exp,
    Fdiv,
    Floor,
    Fmod,
    Hypot,
    Intdiv,
    Log,
    Log10,
    Log2,
    Max,
    Min,
    MtRand,
    Pi,
    Pow,
    Rad2deg,
    Rand,
    RandomInt,
    Round,
    Sin,
    Sinh,
    Sqrt,
    Tan,
    Tanh,
    ElephcPtrIsNull,
    ElephcPtrReadString,
    ElephcPtrWriteString,
    BufferFree,
    BufferLen,
    Ptr,
    PtrGet,
    PtrIsNull,
    PtrNull,
    PtrOffset,
    PtrRead16,
    PtrRead32,
    PtrRead8,
    PtrReadString,
    PtrSet,
    PtrSizeof,
    PtrWrite16,
    PtrWrite32,
    PtrWrite8,
    PtrWriteString,
    ZvalFree,
    ZvalPack,
    ZvalType,
    ZvalUnpack,
    IteratorApply,
    IteratorCount,
    IteratorToArray,
    SplAutoload,
    SplAutoloadCall,
    SplAutoloadExtensions,
    SplAutoloadFunctions,
    SplAutoloadRegister,
    SplAutoloadUnregister,
    SplClasses,
    SplObjectHash,
    SplObjectId,
    Chop,
    Chr,
    Crc32,
    CtypeAlnum,
    CtypeAlpha,
    CtypeDigit,
    CtypeSpace,
    Explode,
    GraphemeStrrev,
    Gzcompress,
    Gzdeflate,
    Gzinflate,
    Gzuncompress,
    Hash,
    HashAlgos,
    HashCopy,
    HashEquals,
    HashFinal,
    HashHmac,
    HashInit,
    HashUpdate,
    Htmlentities,
    Htmlspecialchars,
    Implode,
    InetNtop,
    InetPton,
    Ip2long,
    Lcfirst,
    Long2ip,
    Ltrim,
    MbEregMatch,
    MbStrlen,
    Md5,
    NumberFormat,
    Ord,
    Printf,
    Rtrim,
    Sha1,
    Sprintf,
    Sscanf,
    StrContains,
    StrEndsWith,
    StrIreplace,
    StrPad,
    StrRepeat,
    StrReplace,
    StrSplit,
    StrStartsWith,
    Strcasecmp,
    Strcmp,
    Strpos,
    Strrpos,
    Strstr,
    Substr,
    SubstrReplace,
    Trim,
    Ucfirst,
    Ucwords,
    Vprintf,
    Vsprintf,
    Wordwrap,
    ElephcGmmktimeRaw,
    ElephcMktimeRaw,
    ElephcStrtotimeRaw,
    Checkdate,
    ClassAttributeArgs,
    ClassAttributeNames,
    ClassGetAttributes,
    Date,
    DateDefaultTimezoneGet,
    DateDefaultTimezoneSet,
    Define,
    Defined,
    Exec,
    Getdate,
    Getenv,
    Gmdate,
    Gmmktime,
    Header,
    Hrtime,
    HttpResponseCode,
    JsonDecode,
    JsonEncode,
    JsonLastError,
    JsonLastErrorMsg,
    JsonValidate,
    Localtime,
    Microtime,
    Mktime,
    Passthru,
    PhpUname,
    Phpversion,
    PregMatch,
    PregMatchAll,
    PregReplace,
    PregSplit,
    Putenv,
    Serialize,
    ShellExec,
    Sleep,
    Strtotime,
    System,
    Time,
    Unserialize,
    Usleep,
    Boolval,
    Floatval,
    GetResourceId,
    GetResourceType,
    Gettype,
    Intval,
    IsArray,
    IsBool,
    IsCallable,
    IsFinite,
    IsFloat,
    IsInfinite,
    IsInt,
    IsIterable,
    IsNan,
    IsNull,
    IsNumeric,
    IsObject,
    IsResource,
    IsScalar,
    IsString,
    Settype,
    Strval,
}

impl BuiltinRuntimeTarget {
    /// Refines the first-class callable ABI where the direct PHP signature is broader.
    pub fn refine_first_class_callable_sig(self, sig: &mut crate::types::FunctionSig) {
        use crate::types::PhpType;
        match self {
            BuiltinRuntimeTarget::PregReplaceCallback => {
                if let Some((_, callback_ty)) = sig.params.get_mut(1) {
                    *callback_ty = PhpType::Callable;
                }
            }
            BuiltinRuntimeTarget::ZvalPack => {
                if let Some((_, value_ty)) = sig.params.get_mut(0) {
                    *value_ty = PhpType::Mixed;
                }
                sig.return_type = PhpType::Pointer(None);
            }
            BuiltinRuntimeTarget::ZvalUnpack => {
                if let Some((_, zval_ty)) = sig.params.get_mut(0) {
                    *zval_ty = PhpType::Pointer(None);
                }
                sig.return_type = PhpType::Mixed;
            }
            BuiltinRuntimeTarget::ZvalType => {
                if let Some((_, zval_ty)) = sig.params.get_mut(0) {
                    *zval_ty = PhpType::Pointer(None);
                }
                sig.return_type = PhpType::Int;
            }
            BuiltinRuntimeTarget::ZvalFree => {
                if let Some((_, zval_ty)) = sig.params.get_mut(0) {
                    *zval_ty = PhpType::Pointer(None);
                }
                sig.return_type = PhpType::Void;
            }
            BuiltinRuntimeTarget::BufferLen => {
                if let Some((_, buffer_ty)) = sig.params.get_mut(0) {
                    *buffer_ty = PhpType::Buffer(Box::new(PhpType::Int));
                }
                sig.return_type = PhpType::Int;
            }
            _ => {}
        }
    }

    /// Returns the conservative observable effects for this typed backend operation.
    pub const fn effects(self) -> crate::ir::Effects {
        match self {
            BuiltinRuntimeTarget::Abs |
            BuiltinRuntimeTarget::Acos |
            BuiltinRuntimeTarget::ArrayChunk |
            BuiltinRuntimeTarget::ArrayColumn |
            BuiltinRuntimeTarget::ArrayCombine |
            BuiltinRuntimeTarget::ArrayDiff |
            BuiltinRuntimeTarget::ArrayDiffAssoc |
            BuiltinRuntimeTarget::ArrayDiffKey |
            BuiltinRuntimeTarget::ArrayFill |
            BuiltinRuntimeTarget::ArrayFillKeys |
            BuiltinRuntimeTarget::ArrayFlip |
            BuiltinRuntimeTarget::ArrayIntersect |
            BuiltinRuntimeTarget::ArrayIntersectAssoc |
            BuiltinRuntimeTarget::ArrayIntersectKey |
            BuiltinRuntimeTarget::ArrayIsList |
            BuiltinRuntimeTarget::ArrayKeyExists |
            BuiltinRuntimeTarget::ArrayKeyFirst |
            BuiltinRuntimeTarget::ArrayKeyLast |
            BuiltinRuntimeTarget::ArrayKeys |
            BuiltinRuntimeTarget::ArrayMerge |
            BuiltinRuntimeTarget::ArrayMergeRecursive |
            BuiltinRuntimeTarget::ArrayPad |
            BuiltinRuntimeTarget::ArrayProduct |
            BuiltinRuntimeTarget::ArrayReplace |
            BuiltinRuntimeTarget::ArrayReplaceRecursive |
            BuiltinRuntimeTarget::ArrayReverse |
            BuiltinRuntimeTarget::ArraySearch |
            BuiltinRuntimeTarget::ArraySlice |
            BuiltinRuntimeTarget::ArraySum |
            BuiltinRuntimeTarget::ArrayUnique |
            BuiltinRuntimeTarget::ArrayValues |
            BuiltinRuntimeTarget::Asin |
            BuiltinRuntimeTarget::Atan |
            BuiltinRuntimeTarget::Atan2 |
            BuiltinRuntimeTarget::Boolval |
            BuiltinRuntimeTarget::Ceil |
            BuiltinRuntimeTarget::Chop |
            BuiltinRuntimeTarget::Chr |
            BuiltinRuntimeTarget::Cos |
            BuiltinRuntimeTarget::Cosh |
            BuiltinRuntimeTarget::Count |
            BuiltinRuntimeTarget::Crc32 |
            BuiltinRuntimeTarget::CtypeAlnum |
            BuiltinRuntimeTarget::CtypeAlpha |
            BuiltinRuntimeTarget::CtypeDigit |
            BuiltinRuntimeTarget::CtypeSpace |
            BuiltinRuntimeTarget::Deg2rad |
            BuiltinRuntimeTarget::Exp |
            BuiltinRuntimeTarget::Explode |
            BuiltinRuntimeTarget::Fdiv |
            BuiltinRuntimeTarget::Floatval |
            BuiltinRuntimeTarget::Floor |
            BuiltinRuntimeTarget::Fmod |
            BuiltinRuntimeTarget::GetResourceId |
            BuiltinRuntimeTarget::GetResourceType |
            BuiltinRuntimeTarget::Gettype |
            BuiltinRuntimeTarget::GraphemeStrrev |
            BuiltinRuntimeTarget::HashAlgos |
            BuiltinRuntimeTarget::HashEquals |
            BuiltinRuntimeTarget::Htmlentities |
            BuiltinRuntimeTarget::Htmlspecialchars |
            BuiltinRuntimeTarget::Hypot |
            BuiltinRuntimeTarget::Implode |
            BuiltinRuntimeTarget::InetNtop |
            BuiltinRuntimeTarget::InetPton |
            BuiltinRuntimeTarget::Intval |
            BuiltinRuntimeTarget::Ip2long |
            BuiltinRuntimeTarget::IsArray |
            BuiltinRuntimeTarget::IsBool |
            BuiltinRuntimeTarget::IsFloat |
            BuiltinRuntimeTarget::IsInt |
            BuiltinRuntimeTarget::IsNull |
            BuiltinRuntimeTarget::IsNumeric |
            BuiltinRuntimeTarget::IsObject |
            BuiltinRuntimeTarget::IsResource |
            BuiltinRuntimeTarget::IsScalar |
            BuiltinRuntimeTarget::IsString |
            BuiltinRuntimeTarget::Lcfirst |
            BuiltinRuntimeTarget::Log |
            BuiltinRuntimeTarget::Log10 |
            BuiltinRuntimeTarget::Log2 |
            BuiltinRuntimeTarget::Long2ip |
            BuiltinRuntimeTarget::Ltrim |
            BuiltinRuntimeTarget::Max |
            BuiltinRuntimeTarget::Md5 |
            BuiltinRuntimeTarget::Min |
            BuiltinRuntimeTarget::NumberFormat |
            BuiltinRuntimeTarget::Ord |
            BuiltinRuntimeTarget::Pi |
            BuiltinRuntimeTarget::Pow |
            BuiltinRuntimeTarget::Rad2deg |
            BuiltinRuntimeTarget::Range |
            BuiltinRuntimeTarget::Round |
            BuiltinRuntimeTarget::Rtrim |
            BuiltinRuntimeTarget::Sha1 |
            BuiltinRuntimeTarget::Sin |
            BuiltinRuntimeTarget::Sinh |
            BuiltinRuntimeTarget::Sqrt |
            BuiltinRuntimeTarget::StrContains |
            BuiltinRuntimeTarget::StrEndsWith |
            BuiltinRuntimeTarget::StrIreplace |
            BuiltinRuntimeTarget::StrPad |
            BuiltinRuntimeTarget::StrRepeat |
            BuiltinRuntimeTarget::StrReplace |
            BuiltinRuntimeTarget::StrSplit |
            BuiltinRuntimeTarget::StrStartsWith |
            BuiltinRuntimeTarget::Strcasecmp |
            BuiltinRuntimeTarget::Strcmp |
            BuiltinRuntimeTarget::Strpos |
            BuiltinRuntimeTarget::Strrpos |
            BuiltinRuntimeTarget::Strstr |
            BuiltinRuntimeTarget::Strval |
            BuiltinRuntimeTarget::Substr |
            BuiltinRuntimeTarget::SubstrReplace |
            BuiltinRuntimeTarget::Tan |
            BuiltinRuntimeTarget::Tanh |
            BuiltinRuntimeTarget::Trim |
            BuiltinRuntimeTarget::Ucfirst |
            BuiltinRuntimeTarget::Ucwords |
            BuiltinRuntimeTarget::Wordwrap => crate::ir::Effects::empty(),
            _ => crate::ir::Effects::from_bits_retain(
                crate::ir::Effects::all().bits()
                    & !crate::ir::Effects::REFCOUNT_OP.bits()
                    & !crate::ir::Effects::WRITES_GLOBAL.bits(),
            ),
        }
    }

    /// Returns runtime and linker requirements declared by this typed operation.
    pub const fn requirements(
        self,
    ) -> &'static [crate::builtins::semantics::BuiltinRequirement] {
        use crate::builtins::semantics::BuiltinRequirement;
        match self {
            BuiltinRuntimeTarget::ElephcPharBzip2Archive => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharDecompressArchive => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharGetFileMetadata => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharGetMetadata => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharGetSignatureHash => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharGetSignatureType => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharGetStub => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharGzipArchive => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharListEntries => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharSetCompression => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharSetFileMetadata => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharSetMetadata => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharSetStub => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharSetZipPassword => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharSignHash => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::ElephcPharSignOpenssl => &[BuiltinRequirement::Bridge("elephc_phar")],
            BuiltinRuntimeTarget::Gzcompress => &[BuiltinRequirement::SystemLibrary("z")],
            BuiltinRuntimeTarget::Gzdeflate => &[BuiltinRequirement::SystemLibrary("z")],
            BuiltinRuntimeTarget::Gzinflate => &[BuiltinRequirement::SystemLibrary("z")],
            BuiltinRuntimeTarget::Gzuncompress => &[BuiltinRequirement::SystemLibrary("z")],
            BuiltinRuntimeTarget::Hash => &[BuiltinRequirement::Bridge("elephc_crypto")],
            BuiltinRuntimeTarget::HashCopy => &[BuiltinRequirement::Bridge("elephc_crypto")],
            BuiltinRuntimeTarget::HashFile => &[BuiltinRequirement::Bridge("elephc_crypto")],
            BuiltinRuntimeTarget::HashFinal => &[BuiltinRequirement::Bridge("elephc_crypto")],
            BuiltinRuntimeTarget::HashHmac => &[BuiltinRequirement::Bridge("elephc_crypto")],
            BuiltinRuntimeTarget::HashInit => &[BuiltinRequirement::Bridge("elephc_crypto")],
            BuiltinRuntimeTarget::HashUpdate => &[BuiltinRequirement::Bridge("elephc_crypto")],
            BuiltinRuntimeTarget::MbStrlen => &[BuiltinRequirement::MacOsLibrary("iconv")],
            BuiltinRuntimeTarget::Md5 => &[BuiltinRequirement::Bridge("elephc_crypto")],
            BuiltinRuntimeTarget::Sha1 => &[BuiltinRequirement::Bridge("elephc_crypto")],
            BuiltinRuntimeTarget::StreamSocketEnableCrypto => &[BuiltinRequirement::Bridge("elephc_tls")],
            _ => &[],
        }
    }

    /// Returns whether the operation has a proven generic runtime-callable wrapper.
    pub const fn runtime_callable_supported(self) -> bool {
        matches!(
            self,
            BuiltinRuntimeTarget::Abs
                | BuiltinRuntimeTarget::Boolval
                | BuiltinRuntimeTarget::Floatval
                | BuiltinRuntimeTarget::Gettype
                | BuiltinRuntimeTarget::Intval
                | BuiltinRuntimeTarget::IsArray
                | BuiltinRuntimeTarget::Trim
        )
    }

    /// Returns whether a dynamic source value can use this target's generic wrapper.
    pub fn callable_accepts(self, source: Option<&crate::types::PhpType>) -> bool {
        use crate::types::PhpType;
        let source = source.map(PhpType::codegen_repr);
        match self {
            BuiltinRuntimeTarget::Abs => source.is_none_or(|ty| {
                matches!(
                    ty,
                    PhpType::Bool
                        | PhpType::Float
                        | PhpType::Int
                        | PhpType::Mixed
                        | PhpType::Never
                        | PhpType::TaggedScalar
                        | PhpType::Union(_)
                        | PhpType::Void
                )
            }),
            BuiltinRuntimeTarget::Boolval => source.is_some_and(|ty| {
                matches!(
                    ty,
                    PhpType::AssocArray { .. }
                        | PhpType::Array(_)
                        | PhpType::Bool
                        | PhpType::Float
                        | PhpType::Int
                        | PhpType::Iterable
                        | PhpType::Never
                        | PhpType::Str
                        | PhpType::Void
                )
            }),
            BuiltinRuntimeTarget::Floatval => source.is_some_and(|ty| {
                matches!(
                    ty,
                    PhpType::Bool
                        | PhpType::Float
                        | PhpType::Int
                        | PhpType::Never
                        | PhpType::Str
                        | PhpType::Void
                )
            }),
            BuiltinRuntimeTarget::Intval => source.is_none_or(|ty| {
                matches!(
                    ty,
                    PhpType::Bool
                        | PhpType::Float
                        | PhpType::Int
                        | PhpType::Mixed
                        | PhpType::Never
                        | PhpType::Str
                        | PhpType::Union(_)
                        | PhpType::Void
                )
            }),
            BuiltinRuntimeTarget::Gettype | BuiltinRuntimeTarget::IsArray => true,
            BuiltinRuntimeTarget::Trim => source.is_none_or(|ty| matches!(ty, PhpType::Str)),
            _ => false,
        }
    }

    /// Returns whether this operation requires the optional regex runtime family.
    pub const fn uses_regex_runtime(self) -> bool {
        matches!(
            self,
            BuiltinRuntimeTarget::PregMatch
                | BuiltinRuntimeTarget::PregMatchAll
                | BuiltinRuntimeTarget::PregReplace
                | BuiltinRuntimeTarget::PregReplaceCallback
                | BuiltinRuntimeTarget::PregSplit
        )
    }

    /// Returns whether this operation requires the optional multibyte-length runtime.
    pub const fn uses_mb_strlen_runtime(self) -> bool {
        matches!(self, BuiltinRuntimeTarget::MbStrlen)
    }

    /// Returns whether this operation can publish PHAR bridge helper symbols.
    pub const fn publishes_phar_symbols(self) -> bool {
        matches!(
            self,
            BuiltinRuntimeTarget::ElephcPharListEntries
                | BuiltinRuntimeTarget::ElephcPharGetMetadata
                | BuiltinRuntimeTarget::ElephcPharGetStub
                | BuiltinRuntimeTarget::ElephcPharSetMetadata
                | BuiltinRuntimeTarget::ElephcPharSetStub
                | BuiltinRuntimeTarget::ElephcPharGetFileMetadata
                | BuiltinRuntimeTarget::ElephcPharSetFileMetadata
                | BuiltinRuntimeTarget::ElephcPharGzipArchive
                | BuiltinRuntimeTarget::ElephcPharBzip2Archive
                | BuiltinRuntimeTarget::ElephcPharDecompressArchive
                | BuiltinRuntimeTarget::ElephcPharSignOpenssl
                | BuiltinRuntimeTarget::ElephcPharSignHash
                | BuiltinRuntimeTarget::ElephcPharSetZipPassword
                | BuiltinRuntimeTarget::ElephcPharGetSignatureHash
                | BuiltinRuntimeTarget::ElephcPharGetSignatureType
                | BuiltinRuntimeTarget::FileGetContents
                | BuiltinRuntimeTarget::FilePutContents
                | BuiltinRuntimeTarget::Fopen
        )
    }

    /// Returns the callback operand inspected for runtime string dispatch, if any.
    pub const fn string_callback_operand_index(self) -> Option<usize> {
        match self {
            BuiltinRuntimeTarget::ArrayMap => Some(0),
            BuiltinRuntimeTarget::ArrayFilter
            | BuiltinRuntimeTarget::ArrayReduce
            | BuiltinRuntimeTarget::ArrayWalk
            | BuiltinRuntimeTarget::ArrayWalkRecursive
            | BuiltinRuntimeTarget::Usort
            | BuiltinRuntimeTarget::Uksort
            | BuiltinRuntimeTarget::Uasort
            | BuiltinRuntimeTarget::IteratorApply
            | BuiltinRuntimeTarget::PregReplaceCallback
            | BuiltinRuntimeTarget::ArrayFind
            | BuiltinRuntimeTarget::ArrayAny
            | BuiltinRuntimeTarget::ArrayAll => Some(1),
            BuiltinRuntimeTarget::ArrayUdiff | BuiltinRuntimeTarget::ArrayUintersect => Some(2),
            _ => None,
        }
    }

    /// Returns whether this operation performs dynamic callable lookup.
    pub const fn is_callable_lookup(self) -> bool {
        matches!(self, BuiltinRuntimeTarget::IsCallable)
    }

    /// Returns whether this operation reads a class name from object metadata.
    pub const fn is_class_name_lookup(self) -> bool {
        matches!(self, BuiltinRuntimeTarget::GetClass | BuiltinRuntimeTarget::GetParentClass)
    }

    /// Returns whether this operation registers a stream wrapper or filter class.
    pub const fn is_stream_registration(self) -> bool {
        matches!(
            self,
            BuiltinRuntimeTarget::StreamWrapperRegister
                | BuiltinRuntimeTarget::StreamFilterRegister
        )
    }

    /// Returns the ownership and argument-aliasing contract for this operation.
    pub const fn result_ownership(
        self,
    ) -> crate::builtins::semantics::BuiltinResultOwnership {
        use crate::builtins::semantics::BuiltinResultOwnership;
        if matches!(
            self,
            BuiltinRuntimeTarget::ArrayChunk
                | BuiltinRuntimeTarget::ArrayColumn
                | BuiltinRuntimeTarget::ArrayCombine
                | BuiltinRuntimeTarget::ArrayDiff
                | BuiltinRuntimeTarget::ArrayFill
                | BuiltinRuntimeTarget::ArrayFillKeys
                | BuiltinRuntimeTarget::ArrayIntersect
                | BuiltinRuntimeTarget::ArrayKeys
                | BuiltinRuntimeTarget::ArrayMap
                | BuiltinRuntimeTarget::ArrayMerge
                | BuiltinRuntimeTarget::ArrayPad
                | BuiltinRuntimeTarget::ArrayPop
                | BuiltinRuntimeTarget::ArrayReplace
                | BuiltinRuntimeTarget::ArrayReplaceRecursive
                | BuiltinRuntimeTarget::ArrayReverse
                | BuiltinRuntimeTarget::ArrayShift
                | BuiltinRuntimeTarget::ArraySlice
                | BuiltinRuntimeTarget::ArrayUnique
                | BuiltinRuntimeTarget::ArrayValues
                | BuiltinRuntimeTarget::Explode
                | BuiltinRuntimeTarget::FileGetContents
                | BuiltinRuntimeTarget::IteratorToArray
                | BuiltinRuntimeTarget::ObGetClean
                | BuiltinRuntimeTarget::ObGetContents
                | BuiltinRuntimeTarget::ObGetFlush
                | BuiltinRuntimeTarget::ObGetLength
                | BuiltinRuntimeTarget::ObGetStatus
                | BuiltinRuntimeTarget::ObListHandlers
                | BuiltinRuntimeTarget::PregSplit
                | BuiltinRuntimeTarget::PtrReadString
                | BuiltinRuntimeTarget::Range
                | BuiltinRuntimeTarget::StrSplit
                | BuiltinRuntimeTarget::Strpos
                | BuiltinRuntimeTarget::Strrpos
                | BuiltinRuntimeTarget::ZvalUnpack
        ) {
            BuiltinResultOwnership::Fresh
        } else if matches!(
            self,
            BuiltinRuntimeTarget::Htmlentities
                | BuiltinRuntimeTarget::Htmlspecialchars
                | BuiltinRuntimeTarget::Implode
        ) {
            BuiltinResultOwnership::Independent
        } else {
            BuiltinResultOwnership::MayAliasArguments
        }
    }

    /// Returns the stable textual EIR spelling for diagnostics and snapshots.
    pub fn as_eir(self) -> &'static str {
        match self {
            BuiltinRuntimeTarget::ArrayAll => "array_all",
            BuiltinRuntimeTarget::ArrayAny => "array_any",
            BuiltinRuntimeTarget::ArrayChunk => "array_chunk",
            BuiltinRuntimeTarget::ArrayColumn => "array_column",
            BuiltinRuntimeTarget::ArrayCombine => "array_combine",
            BuiltinRuntimeTarget::ArrayDiff => "array_diff",
            BuiltinRuntimeTarget::ArrayDiffAssoc => "array_diff_assoc",
            BuiltinRuntimeTarget::ArrayDiffKey => "array_diff_key",
            BuiltinRuntimeTarget::ArrayFill => "array_fill",
            BuiltinRuntimeTarget::ArrayFillKeys => "array_fill_keys",
            BuiltinRuntimeTarget::ArrayFilter => "array_filter",
            BuiltinRuntimeTarget::ArrayFind => "array_find",
            BuiltinRuntimeTarget::ArrayFlip => "array_flip",
            BuiltinRuntimeTarget::ArrayIntersect => "array_intersect",
            BuiltinRuntimeTarget::ArrayIntersectAssoc => "array_intersect_assoc",
            BuiltinRuntimeTarget::ArrayIntersectKey => "array_intersect_key",
            BuiltinRuntimeTarget::ArrayIsList => "array_is_list",
            BuiltinRuntimeTarget::ArrayKeyExists => "array_key_exists",
            BuiltinRuntimeTarget::ArrayKeyFirst => "array_key_first",
            BuiltinRuntimeTarget::ArrayKeyLast => "array_key_last",
            BuiltinRuntimeTarget::ArrayKeys => "array_keys",
            BuiltinRuntimeTarget::ArrayMap => "array_map",
            BuiltinRuntimeTarget::ArrayMerge => "array_merge",
            BuiltinRuntimeTarget::ArrayMergeRecursive => "array_merge_recursive",
            BuiltinRuntimeTarget::ArrayMultisort => "array_multisort",
            BuiltinRuntimeTarget::ArrayPad => "array_pad",
            BuiltinRuntimeTarget::ArrayPop => "array_pop",
            BuiltinRuntimeTarget::ArrayProduct => "array_product",
            BuiltinRuntimeTarget::ArrayPush => "array_push",
            BuiltinRuntimeTarget::ArrayRand => "array_rand",
            BuiltinRuntimeTarget::ArrayReduce => "array_reduce",
            BuiltinRuntimeTarget::ArrayReplace => "array_replace",
            BuiltinRuntimeTarget::ArrayReplaceRecursive => "array_replace_recursive",
            BuiltinRuntimeTarget::ArrayReverse => "array_reverse",
            BuiltinRuntimeTarget::ArraySearch => "array_search",
            BuiltinRuntimeTarget::ArrayShift => "array_shift",
            BuiltinRuntimeTarget::ArraySlice => "array_slice",
            BuiltinRuntimeTarget::ArraySplice => "array_splice",
            BuiltinRuntimeTarget::ArraySum => "array_sum",
            BuiltinRuntimeTarget::ArrayUdiff => "array_udiff",
            BuiltinRuntimeTarget::ArrayUintersect => "array_uintersect",
            BuiltinRuntimeTarget::ArrayUnique => "array_unique",
            BuiltinRuntimeTarget::ArrayUnshift => "array_unshift",
            BuiltinRuntimeTarget::ArrayValues => "array_values",
            BuiltinRuntimeTarget::ArrayWalk => "array_walk",
            BuiltinRuntimeTarget::ArrayWalkRecursive => "array_walk_recursive",
            BuiltinRuntimeTarget::Arsort => "arsort",
            BuiltinRuntimeTarget::Asort => "asort",
            BuiltinRuntimeTarget::Count => "count",
            BuiltinRuntimeTarget::InArray => "in_array",
            BuiltinRuntimeTarget::Krsort => "krsort",
            BuiltinRuntimeTarget::Ksort => "ksort",
            BuiltinRuntimeTarget::Natcasesort => "natcasesort",
            BuiltinRuntimeTarget::Natsort => "natsort",
            BuiltinRuntimeTarget::Range => "range",
            BuiltinRuntimeTarget::Rsort => "rsort",
            BuiltinRuntimeTarget::Shuffle => "shuffle",
            BuiltinRuntimeTarget::Sort => "sort",
            BuiltinRuntimeTarget::Uasort => "uasort",
            BuiltinRuntimeTarget::Uksort => "uksort",
            BuiltinRuntimeTarget::Usort => "usort",
            BuiltinRuntimeTarget::CallUserFunc => "call_user_func",
            BuiltinRuntimeTarget::CallUserFuncArray => "call_user_func_array",
            BuiltinRuntimeTarget::ClassAlias => "class_alias",
            BuiltinRuntimeTarget::ClassExists => "class_exists",
            BuiltinRuntimeTarget::ClassImplements => "class_implements",
            BuiltinRuntimeTarget::ClassParents => "class_parents",
            BuiltinRuntimeTarget::ClassUses => "class_uses",
            BuiltinRuntimeTarget::EnumExists => "enum_exists",
            BuiltinRuntimeTarget::FunctionExists => "function_exists",
            BuiltinRuntimeTarget::GetClass => "get_class",
            BuiltinRuntimeTarget::GetDeclaredClasses => "get_declared_classes",
            BuiltinRuntimeTarget::GetDeclaredInterfaces => "get_declared_interfaces",
            BuiltinRuntimeTarget::GetDeclaredTraits => "get_declared_traits",
            BuiltinRuntimeTarget::GetParentClass => "get_parent_class",
            BuiltinRuntimeTarget::InterfaceExists => "interface_exists",
            BuiltinRuntimeTarget::IsA => "is_a",
            BuiltinRuntimeTarget::IsSubclassOf => "is_subclass_of",
            BuiltinRuntimeTarget::MethodExists => "method_exists",
            BuiltinRuntimeTarget::PregReplaceCallback => "preg_replace_callback",
            BuiltinRuntimeTarget::PropertyExists => "property_exists",
            BuiltinRuntimeTarget::TraitExists => "trait_exists",
            BuiltinRuntimeTarget::ElephcPharBzip2Archive => "__elephc_phar_bzip2_archive",
            BuiltinRuntimeTarget::ElephcPharDecompressArchive => "__elephc_phar_decompress_archive",
            BuiltinRuntimeTarget::ElephcPharGetFileMetadata => "__elephc_phar_get_file_metadata",
            BuiltinRuntimeTarget::ElephcPharGetMetadata => "__elephc_phar_get_metadata",
            BuiltinRuntimeTarget::ElephcPharGetSignatureHash => "__elephc_phar_get_signature_hash",
            BuiltinRuntimeTarget::ElephcPharGetSignatureType => "__elephc_phar_get_signature_type",
            BuiltinRuntimeTarget::ElephcPharGetStub => "__elephc_phar_get_stub",
            BuiltinRuntimeTarget::ElephcPharGzipArchive => "__elephc_phar_gzip_archive",
            BuiltinRuntimeTarget::ElephcPharListEntries => "__elephc_phar_list_entries",
            BuiltinRuntimeTarget::ElephcPharSetCompression => "__elephc_phar_set_compression",
            BuiltinRuntimeTarget::ElephcPharSetFileMetadata => "__elephc_phar_set_file_metadata",
            BuiltinRuntimeTarget::ElephcPharSetMetadata => "__elephc_phar_set_metadata",
            BuiltinRuntimeTarget::ElephcPharSetStub => "__elephc_phar_set_stub",
            BuiltinRuntimeTarget::ElephcPharSetZipPassword => "__elephc_phar_set_zip_password",
            BuiltinRuntimeTarget::ElephcPharSignHash => "__elephc_phar_sign_hash",
            BuiltinRuntimeTarget::ElephcPharSignOpenssl => "__elephc_phar_sign_openssl",
            BuiltinRuntimeTarget::Basename => "basename",
            BuiltinRuntimeTarget::Chdir => "chdir",
            BuiltinRuntimeTarget::Chgrp => "chgrp",
            BuiltinRuntimeTarget::Chmod => "chmod",
            BuiltinRuntimeTarget::Chown => "chown",
            BuiltinRuntimeTarget::Clearstatcache => "clearstatcache",
            BuiltinRuntimeTarget::Closedir => "closedir",
            BuiltinRuntimeTarget::Copy => "copy",
            BuiltinRuntimeTarget::Dirname => "dirname",
            BuiltinRuntimeTarget::DiskFreeSpace => "disk_free_space",
            BuiltinRuntimeTarget::DiskTotalSpace => "disk_total_space",
            BuiltinRuntimeTarget::Fclose => "fclose",
            BuiltinRuntimeTarget::Fdatasync => "fdatasync",
            BuiltinRuntimeTarget::Feof => "feof",
            BuiltinRuntimeTarget::Fflush => "fflush",
            BuiltinRuntimeTarget::Fgetc => "fgetc",
            BuiltinRuntimeTarget::Fgetcsv => "fgetcsv",
            BuiltinRuntimeTarget::Fgets => "fgets",
            BuiltinRuntimeTarget::File => "file",
            BuiltinRuntimeTarget::FileExists => "file_exists",
            BuiltinRuntimeTarget::FileGetContents => "file_get_contents",
            BuiltinRuntimeTarget::FilePutContents => "file_put_contents",
            BuiltinRuntimeTarget::Fileatime => "fileatime",
            BuiltinRuntimeTarget::Filectime => "filectime",
            BuiltinRuntimeTarget::Filegroup => "filegroup",
            BuiltinRuntimeTarget::Fileinode => "fileinode",
            BuiltinRuntimeTarget::Filemtime => "filemtime",
            BuiltinRuntimeTarget::Fileowner => "fileowner",
            BuiltinRuntimeTarget::Fileperms => "fileperms",
            BuiltinRuntimeTarget::Filesize => "filesize",
            BuiltinRuntimeTarget::Filetype => "filetype",
            BuiltinRuntimeTarget::Flock => "flock",
            BuiltinRuntimeTarget::Fnmatch => "fnmatch",
            BuiltinRuntimeTarget::Fopen => "fopen",
            BuiltinRuntimeTarget::Fpassthru => "fpassthru",
            BuiltinRuntimeTarget::Fprintf => "fprintf",
            BuiltinRuntimeTarget::Fputcsv => "fputcsv",
            BuiltinRuntimeTarget::Fread => "fread",
            BuiltinRuntimeTarget::Fscanf => "fscanf",
            BuiltinRuntimeTarget::Fseek => "fseek",
            BuiltinRuntimeTarget::Fsockopen => "fsockopen",
            BuiltinRuntimeTarget::Fstat => "fstat",
            BuiltinRuntimeTarget::Fsync => "fsync",
            BuiltinRuntimeTarget::Ftell => "ftell",
            BuiltinRuntimeTarget::Ftruncate => "ftruncate",
            BuiltinRuntimeTarget::Fwrite => "fwrite",
            BuiltinRuntimeTarget::Getcwd => "getcwd",
            BuiltinRuntimeTarget::Gethostbyaddr => "gethostbyaddr",
            BuiltinRuntimeTarget::Gethostbyname => "gethostbyname",
            BuiltinRuntimeTarget::Gethostname => "gethostname",
            BuiltinRuntimeTarget::Getprotobyname => "getprotobyname",
            BuiltinRuntimeTarget::Getprotobynumber => "getprotobynumber",
            BuiltinRuntimeTarget::Getservbyname => "getservbyname",
            BuiltinRuntimeTarget::Getservbyport => "getservbyport",
            BuiltinRuntimeTarget::Glob => "glob",
            BuiltinRuntimeTarget::HashFile => "hash_file",
            BuiltinRuntimeTarget::IsDir => "is_dir",
            BuiltinRuntimeTarget::IsExecutable => "is_executable",
            BuiltinRuntimeTarget::IsFile => "is_file",
            BuiltinRuntimeTarget::IsLink => "is_link",
            BuiltinRuntimeTarget::IsReadable => "is_readable",
            BuiltinRuntimeTarget::IsWritable => "is_writable",
            BuiltinRuntimeTarget::IsWriteable => "is_writeable",
            BuiltinRuntimeTarget::Lchgrp => "lchgrp",
            BuiltinRuntimeTarget::Lchown => "lchown",
            BuiltinRuntimeTarget::Link => "link",
            BuiltinRuntimeTarget::Linkinfo => "linkinfo",
            BuiltinRuntimeTarget::Lstat => "lstat",
            BuiltinRuntimeTarget::Mkdir => "mkdir",
            BuiltinRuntimeTarget::ObClean => "ob_clean",
            BuiltinRuntimeTarget::ObEndClean => "ob_end_clean",
            BuiltinRuntimeTarget::ObEndFlush => "ob_end_flush",
            BuiltinRuntimeTarget::ObFlush => "ob_flush",
            BuiltinRuntimeTarget::ObGetClean => "ob_get_clean",
            BuiltinRuntimeTarget::ObGetContents => "ob_get_contents",
            BuiltinRuntimeTarget::ObGetFlush => "ob_get_flush",
            BuiltinRuntimeTarget::ObGetLength => "ob_get_length",
            BuiltinRuntimeTarget::ObGetLevel => "ob_get_level",
            BuiltinRuntimeTarget::ObGetStatus => "ob_get_status",
            BuiltinRuntimeTarget::ObImplicitFlush => "ob_implicit_flush",
            BuiltinRuntimeTarget::ObListHandlers => "ob_list_handlers",
            BuiltinRuntimeTarget::ObStart => "ob_start",
            BuiltinRuntimeTarget::Opendir => "opendir",
            BuiltinRuntimeTarget::Pathinfo => "pathinfo",
            BuiltinRuntimeTarget::Pclose => "pclose",
            BuiltinRuntimeTarget::Pfsockopen => "pfsockopen",
            BuiltinRuntimeTarget::Popen => "popen",
            BuiltinRuntimeTarget::PrintR => "print_r",
            BuiltinRuntimeTarget::Readdir => "readdir",
            BuiltinRuntimeTarget::Readfile => "readfile",
            BuiltinRuntimeTarget::Readline => "readline",
            BuiltinRuntimeTarget::Readlink => "readlink",
            BuiltinRuntimeTarget::Realpath => "realpath",
            BuiltinRuntimeTarget::RealpathCacheGet => "realpath_cache_get",
            BuiltinRuntimeTarget::RealpathCacheSize => "realpath_cache_size",
            BuiltinRuntimeTarget::Rename => "rename",
            BuiltinRuntimeTarget::Rewind => "rewind",
            BuiltinRuntimeTarget::Rewinddir => "rewinddir",
            BuiltinRuntimeTarget::Rmdir => "rmdir",
            BuiltinRuntimeTarget::Scandir => "scandir",
            BuiltinRuntimeTarget::Stat => "stat",
            BuiltinRuntimeTarget::StreamBucketAppend => "stream_bucket_append",
            BuiltinRuntimeTarget::StreamBucketMakeWriteable => "stream_bucket_make_writeable",
            BuiltinRuntimeTarget::StreamBucketNew => "stream_bucket_new",
            BuiltinRuntimeTarget::StreamBucketPrepend => "stream_bucket_prepend",
            BuiltinRuntimeTarget::StreamContextCreate => "stream_context_create",
            BuiltinRuntimeTarget::StreamContextGetDefault => "stream_context_get_default",
            BuiltinRuntimeTarget::StreamContextGetOptions => "stream_context_get_options",
            BuiltinRuntimeTarget::StreamContextGetParams => "stream_context_get_params",
            BuiltinRuntimeTarget::StreamContextSetDefault => "stream_context_set_default",
            BuiltinRuntimeTarget::StreamContextSetOption => "stream_context_set_option",
            BuiltinRuntimeTarget::StreamContextSetParams => "stream_context_set_params",
            BuiltinRuntimeTarget::StreamCopyToStream => "stream_copy_to_stream",
            BuiltinRuntimeTarget::StreamFilterAppend => "stream_filter_append",
            BuiltinRuntimeTarget::StreamFilterPrepend => "stream_filter_prepend",
            BuiltinRuntimeTarget::StreamFilterRegister => "stream_filter_register",
            BuiltinRuntimeTarget::StreamFilterRemove => "stream_filter_remove",
            BuiltinRuntimeTarget::StreamGetContents => "stream_get_contents",
            BuiltinRuntimeTarget::StreamGetFilters => "stream_get_filters",
            BuiltinRuntimeTarget::StreamGetLine => "stream_get_line",
            BuiltinRuntimeTarget::StreamGetMetaData => "stream_get_meta_data",
            BuiltinRuntimeTarget::StreamGetTransports => "stream_get_transports",
            BuiltinRuntimeTarget::StreamGetWrappers => "stream_get_wrappers",
            BuiltinRuntimeTarget::StreamIsLocal => "stream_is_local",
            BuiltinRuntimeTarget::StreamIsatty => "stream_isatty",
            BuiltinRuntimeTarget::StreamResolveIncludePath => "stream_resolve_include_path",
            BuiltinRuntimeTarget::StreamSelect => "stream_select",
            BuiltinRuntimeTarget::StreamSetBlocking => "stream_set_blocking",
            BuiltinRuntimeTarget::StreamSetChunkSize => "stream_set_chunk_size",
            BuiltinRuntimeTarget::StreamSetReadBuffer => "stream_set_read_buffer",
            BuiltinRuntimeTarget::StreamSetTimeout => "stream_set_timeout",
            BuiltinRuntimeTarget::StreamSetWriteBuffer => "stream_set_write_buffer",
            BuiltinRuntimeTarget::StreamSocketAccept => "stream_socket_accept",
            BuiltinRuntimeTarget::StreamSocketClient => "stream_socket_client",
            BuiltinRuntimeTarget::StreamSocketEnableCrypto => "stream_socket_enable_crypto",
            BuiltinRuntimeTarget::StreamSocketGetName => "stream_socket_get_name",
            BuiltinRuntimeTarget::StreamSocketPair => "stream_socket_pair",
            BuiltinRuntimeTarget::StreamSocketRecvfrom => "stream_socket_recvfrom",
            BuiltinRuntimeTarget::StreamSocketSendto => "stream_socket_sendto",
            BuiltinRuntimeTarget::StreamSocketServer => "stream_socket_server",
            BuiltinRuntimeTarget::StreamSocketShutdown => "stream_socket_shutdown",
            BuiltinRuntimeTarget::StreamSupportsLock => "stream_supports_lock",
            BuiltinRuntimeTarget::StreamWrapperRegister => "stream_wrapper_register",
            BuiltinRuntimeTarget::StreamWrapperRestore => "stream_wrapper_restore",
            BuiltinRuntimeTarget::StreamWrapperUnregister => "stream_wrapper_unregister",
            BuiltinRuntimeTarget::Symlink => "symlink",
            BuiltinRuntimeTarget::SysGetTempDir => "sys_get_temp_dir",
            BuiltinRuntimeTarget::Tempnam => "tempnam",
            BuiltinRuntimeTarget::Tmpfile => "tmpfile",
            BuiltinRuntimeTarget::Touch => "touch",
            BuiltinRuntimeTarget::Umask => "umask",
            BuiltinRuntimeTarget::Unlink => "unlink",
            BuiltinRuntimeTarget::VarDump => "var_dump",
            BuiltinRuntimeTarget::Vfprintf => "vfprintf",
            BuiltinRuntimeTarget::Abs => "abs",
            BuiltinRuntimeTarget::Acos => "acos",
            BuiltinRuntimeTarget::Asin => "asin",
            BuiltinRuntimeTarget::Atan => "atan",
            BuiltinRuntimeTarget::Atan2 => "atan2",
            BuiltinRuntimeTarget::Ceil => "ceil",
            BuiltinRuntimeTarget::Clamp => "clamp",
            BuiltinRuntimeTarget::Cos => "cos",
            BuiltinRuntimeTarget::Cosh => "cosh",
            BuiltinRuntimeTarget::Deg2rad => "deg2rad",
            BuiltinRuntimeTarget::Exp => "exp",
            BuiltinRuntimeTarget::Fdiv => "fdiv",
            BuiltinRuntimeTarget::Floor => "floor",
            BuiltinRuntimeTarget::Fmod => "fmod",
            BuiltinRuntimeTarget::Hypot => "hypot",
            BuiltinRuntimeTarget::Intdiv => "intdiv",
            BuiltinRuntimeTarget::Log => "log",
            BuiltinRuntimeTarget::Log10 => "log10",
            BuiltinRuntimeTarget::Log2 => "log2",
            BuiltinRuntimeTarget::Max => "max",
            BuiltinRuntimeTarget::Min => "min",
            BuiltinRuntimeTarget::MtRand => "mt_rand",
            BuiltinRuntimeTarget::Pi => "pi",
            BuiltinRuntimeTarget::Pow => "pow",
            BuiltinRuntimeTarget::Rad2deg => "rad2deg",
            BuiltinRuntimeTarget::Rand => "rand",
            BuiltinRuntimeTarget::RandomInt => "random_int",
            BuiltinRuntimeTarget::Round => "round",
            BuiltinRuntimeTarget::Sin => "sin",
            BuiltinRuntimeTarget::Sinh => "sinh",
            BuiltinRuntimeTarget::Sqrt => "sqrt",
            BuiltinRuntimeTarget::Tan => "tan",
            BuiltinRuntimeTarget::Tanh => "tanh",
            BuiltinRuntimeTarget::ElephcPtrIsNull => "__elephc_ptr_is_null",
            BuiltinRuntimeTarget::ElephcPtrReadString => "__elephc_ptr_read_string",
            BuiltinRuntimeTarget::ElephcPtrWriteString => "__elephc_ptr_write_string",
            BuiltinRuntimeTarget::BufferFree => "buffer_free",
            BuiltinRuntimeTarget::BufferLen => "buffer_len",
            BuiltinRuntimeTarget::Ptr => "ptr",
            BuiltinRuntimeTarget::PtrGet => "ptr_get",
            BuiltinRuntimeTarget::PtrIsNull => "ptr_is_null",
            BuiltinRuntimeTarget::PtrNull => "ptr_null",
            BuiltinRuntimeTarget::PtrOffset => "ptr_offset",
            BuiltinRuntimeTarget::PtrRead16 => "ptr_read16",
            BuiltinRuntimeTarget::PtrRead32 => "ptr_read32",
            BuiltinRuntimeTarget::PtrRead8 => "ptr_read8",
            BuiltinRuntimeTarget::PtrReadString => "ptr_read_string",
            BuiltinRuntimeTarget::PtrSet => "ptr_set",
            BuiltinRuntimeTarget::PtrSizeof => "ptr_sizeof",
            BuiltinRuntimeTarget::PtrWrite16 => "ptr_write16",
            BuiltinRuntimeTarget::PtrWrite32 => "ptr_write32",
            BuiltinRuntimeTarget::PtrWrite8 => "ptr_write8",
            BuiltinRuntimeTarget::PtrWriteString => "ptr_write_string",
            BuiltinRuntimeTarget::ZvalFree => "zval_free",
            BuiltinRuntimeTarget::ZvalPack => "zval_pack",
            BuiltinRuntimeTarget::ZvalType => "zval_type",
            BuiltinRuntimeTarget::ZvalUnpack => "zval_unpack",
            BuiltinRuntimeTarget::IteratorApply => "iterator_apply",
            BuiltinRuntimeTarget::IteratorCount => "iterator_count",
            BuiltinRuntimeTarget::IteratorToArray => "iterator_to_array",
            BuiltinRuntimeTarget::SplAutoload => "spl_autoload",
            BuiltinRuntimeTarget::SplAutoloadCall => "spl_autoload_call",
            BuiltinRuntimeTarget::SplAutoloadExtensions => "spl_autoload_extensions",
            BuiltinRuntimeTarget::SplAutoloadFunctions => "spl_autoload_functions",
            BuiltinRuntimeTarget::SplAutoloadRegister => "spl_autoload_register",
            BuiltinRuntimeTarget::SplAutoloadUnregister => "spl_autoload_unregister",
            BuiltinRuntimeTarget::SplClasses => "spl_classes",
            BuiltinRuntimeTarget::SplObjectHash => "spl_object_hash",
            BuiltinRuntimeTarget::SplObjectId => "spl_object_id",
            BuiltinRuntimeTarget::Chop => "chop",
            BuiltinRuntimeTarget::Chr => "chr",
            BuiltinRuntimeTarget::Crc32 => "crc32",
            BuiltinRuntimeTarget::CtypeAlnum => "ctype_alnum",
            BuiltinRuntimeTarget::CtypeAlpha => "ctype_alpha",
            BuiltinRuntimeTarget::CtypeDigit => "ctype_digit",
            BuiltinRuntimeTarget::CtypeSpace => "ctype_space",
            BuiltinRuntimeTarget::Explode => "explode",
            BuiltinRuntimeTarget::GraphemeStrrev => "grapheme_strrev",
            BuiltinRuntimeTarget::Gzcompress => "gzcompress",
            BuiltinRuntimeTarget::Gzdeflate => "gzdeflate",
            BuiltinRuntimeTarget::Gzinflate => "gzinflate",
            BuiltinRuntimeTarget::Gzuncompress => "gzuncompress",
            BuiltinRuntimeTarget::Hash => "hash",
            BuiltinRuntimeTarget::HashAlgos => "hash_algos",
            BuiltinRuntimeTarget::HashCopy => "hash_copy",
            BuiltinRuntimeTarget::HashEquals => "hash_equals",
            BuiltinRuntimeTarget::HashFinal => "hash_final",
            BuiltinRuntimeTarget::HashHmac => "hash_hmac",
            BuiltinRuntimeTarget::HashInit => "hash_init",
            BuiltinRuntimeTarget::HashUpdate => "hash_update",
            BuiltinRuntimeTarget::Htmlentities => "htmlentities",
            BuiltinRuntimeTarget::Htmlspecialchars => "htmlspecialchars",
            BuiltinRuntimeTarget::Implode => "implode",
            BuiltinRuntimeTarget::InetNtop => "inet_ntop",
            BuiltinRuntimeTarget::InetPton => "inet_pton",
            BuiltinRuntimeTarget::Ip2long => "ip2long",
            BuiltinRuntimeTarget::Lcfirst => "lcfirst",
            BuiltinRuntimeTarget::Long2ip => "long2ip",
            BuiltinRuntimeTarget::Ltrim => "ltrim",
            BuiltinRuntimeTarget::MbEregMatch => "mb_ereg_match",
            BuiltinRuntimeTarget::MbStrlen => "mb_strlen",
            BuiltinRuntimeTarget::Md5 => "md5",
            BuiltinRuntimeTarget::NumberFormat => "number_format",
            BuiltinRuntimeTarget::Ord => "ord",
            BuiltinRuntimeTarget::Printf => "printf",
            BuiltinRuntimeTarget::Rtrim => "rtrim",
            BuiltinRuntimeTarget::Sha1 => "sha1",
            BuiltinRuntimeTarget::Sprintf => "sprintf",
            BuiltinRuntimeTarget::Sscanf => "sscanf",
            BuiltinRuntimeTarget::StrContains => "str_contains",
            BuiltinRuntimeTarget::StrEndsWith => "str_ends_with",
            BuiltinRuntimeTarget::StrIreplace => "str_ireplace",
            BuiltinRuntimeTarget::StrPad => "str_pad",
            BuiltinRuntimeTarget::StrRepeat => "str_repeat",
            BuiltinRuntimeTarget::StrReplace => "str_replace",
            BuiltinRuntimeTarget::StrSplit => "str_split",
            BuiltinRuntimeTarget::StrStartsWith => "str_starts_with",
            BuiltinRuntimeTarget::Strcasecmp => "strcasecmp",
            BuiltinRuntimeTarget::Strcmp => "strcmp",
            BuiltinRuntimeTarget::Strpos => "strpos",
            BuiltinRuntimeTarget::Strrpos => "strrpos",
            BuiltinRuntimeTarget::Strstr => "strstr",
            BuiltinRuntimeTarget::Substr => "substr",
            BuiltinRuntimeTarget::SubstrReplace => "substr_replace",
            BuiltinRuntimeTarget::Trim => "trim",
            BuiltinRuntimeTarget::Ucfirst => "ucfirst",
            BuiltinRuntimeTarget::Ucwords => "ucwords",
            BuiltinRuntimeTarget::Vprintf => "vprintf",
            BuiltinRuntimeTarget::Vsprintf => "vsprintf",
            BuiltinRuntimeTarget::Wordwrap => "wordwrap",
            BuiltinRuntimeTarget::ElephcGmmktimeRaw => "__elephc_gmmktime_raw",
            BuiltinRuntimeTarget::ElephcMktimeRaw => "__elephc_mktime_raw",
            BuiltinRuntimeTarget::ElephcStrtotimeRaw => "__elephc_strtotime_raw",
            BuiltinRuntimeTarget::Checkdate => "checkdate",
            BuiltinRuntimeTarget::ClassAttributeArgs => "class_attribute_args",
            BuiltinRuntimeTarget::ClassAttributeNames => "class_attribute_names",
            BuiltinRuntimeTarget::ClassGetAttributes => "class_get_attributes",
            BuiltinRuntimeTarget::Date => "date",
            BuiltinRuntimeTarget::DateDefaultTimezoneGet => "date_default_timezone_get",
            BuiltinRuntimeTarget::DateDefaultTimezoneSet => "date_default_timezone_set",
            BuiltinRuntimeTarget::Define => "define",
            BuiltinRuntimeTarget::Defined => "defined",
            BuiltinRuntimeTarget::Exec => "exec",
            BuiltinRuntimeTarget::Getdate => "getdate",
            BuiltinRuntimeTarget::Getenv => "getenv",
            BuiltinRuntimeTarget::Gmdate => "gmdate",
            BuiltinRuntimeTarget::Gmmktime => "gmmktime",
            BuiltinRuntimeTarget::Header => "header",
            BuiltinRuntimeTarget::Hrtime => "hrtime",
            BuiltinRuntimeTarget::HttpResponseCode => "http_response_code",
            BuiltinRuntimeTarget::JsonDecode => "json_decode",
            BuiltinRuntimeTarget::JsonEncode => "json_encode",
            BuiltinRuntimeTarget::JsonLastError => "json_last_error",
            BuiltinRuntimeTarget::JsonLastErrorMsg => "json_last_error_msg",
            BuiltinRuntimeTarget::JsonValidate => "json_validate",
            BuiltinRuntimeTarget::Localtime => "localtime",
            BuiltinRuntimeTarget::Microtime => "microtime",
            BuiltinRuntimeTarget::Mktime => "mktime",
            BuiltinRuntimeTarget::Passthru => "passthru",
            BuiltinRuntimeTarget::PhpUname => "php_uname",
            BuiltinRuntimeTarget::Phpversion => "phpversion",
            BuiltinRuntimeTarget::PregMatch => "preg_match",
            BuiltinRuntimeTarget::PregMatchAll => "preg_match_all",
            BuiltinRuntimeTarget::PregReplace => "preg_replace",
            BuiltinRuntimeTarget::PregSplit => "preg_split",
            BuiltinRuntimeTarget::Putenv => "putenv",
            BuiltinRuntimeTarget::Serialize => "serialize",
            BuiltinRuntimeTarget::ShellExec => "shell_exec",
            BuiltinRuntimeTarget::Sleep => "sleep",
            BuiltinRuntimeTarget::Strtotime => "strtotime",
            BuiltinRuntimeTarget::System => "system",
            BuiltinRuntimeTarget::Time => "time",
            BuiltinRuntimeTarget::Unserialize => "unserialize",
            BuiltinRuntimeTarget::Usleep => "usleep",
            BuiltinRuntimeTarget::Boolval => "boolval",
            BuiltinRuntimeTarget::Floatval => "floatval",
            BuiltinRuntimeTarget::GetResourceId => "get_resource_id",
            BuiltinRuntimeTarget::GetResourceType => "get_resource_type",
            BuiltinRuntimeTarget::Gettype => "gettype",
            BuiltinRuntimeTarget::Intval => "intval",
            BuiltinRuntimeTarget::IsArray => "is_array",
            BuiltinRuntimeTarget::IsBool => "is_bool",
            BuiltinRuntimeTarget::IsCallable => "is_callable",
            BuiltinRuntimeTarget::IsFinite => "is_finite",
            BuiltinRuntimeTarget::IsFloat => "is_float",
            BuiltinRuntimeTarget::IsInfinite => "is_infinite",
            BuiltinRuntimeTarget::IsInt => "is_int",
            BuiltinRuntimeTarget::IsIterable => "is_iterable",
            BuiltinRuntimeTarget::IsNan => "is_nan",
            BuiltinRuntimeTarget::IsNull => "is_null",
            BuiltinRuntimeTarget::IsNumeric => "is_numeric",
            BuiltinRuntimeTarget::IsObject => "is_object",
            BuiltinRuntimeTarget::IsResource => "is_resource",
            BuiltinRuntimeTarget::IsScalar => "is_scalar",
            BuiltinRuntimeTarget::IsString => "is_string",
            BuiltinRuntimeTarget::Settype => "settype",
            BuiltinRuntimeTarget::Strval => "strval",
        }
    }
}
